// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  // Returns the current platform's Firebase options
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase options for web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU50GSNDGLb8Zx0dfJAM2w6pV_u0QlYq8',
    appId: '1:317322974979:web:5f8c9c497841fd3ee77b36',
    messagingSenderId: '317322974979',
    projectId: 'evdeai-564ce',
    authDomain: 'evdeai-564ce.firebaseapp.com',
    storageBucket: 'evdeai-564ce.firebasestorage.app',
    measurementId: 'G-B6KKQZGVSH',
  );

  // Firebase options for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHmC5safEOBkU0k-DauCyx3srrHA2rVY',
    appId: '1:317322974979:android:4d29179de49277d7e77b36',
    messagingSenderId: '317322974979',
    projectId: 'evdeai-564ce',
    storageBucket: 'evdeai-564ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd9zWYwQGdJGPMn2_Q-VCW-WLrgJhXIZM',
    appId: '1:317322974979:ios:f929f7dca9f51f3de77b36',
    messagingSenderId: '317322974979',
    projectId: 'evdeai-564ce',
    storageBucket: 'evdeai-564ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationEvdeai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd9zWYwQGdJGPMn2_Q-VCW-WLrgJhXIZM',
    appId: '1:317322974979:ios:f929f7dca9f51f3de77b36',
    messagingSenderId: '317322974979',
    projectId: 'evdeai-564ce',
    storageBucket: 'evdeai-564ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationEvdeai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU50GSNDGLb8Zx0dfJAM2w6pV_u0QlYq8',
    appId: '1:317322974979:web:6d245b18ff10bbcce77b36',
    messagingSenderId: '317322974979',
    projectId: 'evdeai-564ce',
    authDomain: 'evdeai-564ce.firebaseapp.com',
    storageBucket: 'evdeai-564ce.firebasestorage.app',
    measurementId: 'G-S75LTTP676',
  );
}
