// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  // Returns the current platform's Firebase options
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LJrBxdTSxsGvgDBvZwaUGAPnFVDZQOA',
    appId: '1:478869573918:web:431013ade0d3aa3c4ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    authDomain: 'evde-ai.firebaseapp.com',
    storageBucket: 'evde-ai.appspot.com',
    measurementId: 'G-94T782M7FG',
  );

  // Firebase options for web

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgFKxSVM6Rb6Di_PD6cApj37a1b_Sa0CE',
    appId: '1:478869573918:android:9be03319b303b7e74ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    storageBucket: 'evde-ai.appspot.com',
  );

  // Firebase options for Android

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOUaj8etx87DY6EdSofSSHGJm-P_NgmY',
    appId: '1:478869573918:ios:dfbe477b1c42c4804ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    storageBucket: 'evde-ai.appspot.com',
    iosBundleId: 'com.example.flutterApplicationEvdeai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLOUaj8etx87DY6EdSofSSHGJm-P_NgmY',
    appId: '1:478869573918:ios:dfbe477b1c42c4804ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    storageBucket: 'evde-ai.appspot.com',
    iosBundleId: 'com.example.flutterApplicationEvdeai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4LJrBxdTSxsGvgDBvZwaUGAPnFVDZQOA',
    appId: '1:478869573918:web:431013ade0d3aa3c4ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    authDomain: 'evde-ai.firebaseapp.com',
    storageBucket: 'evde-ai.appspot.com',
    measurementId: 'G-94T782M7FG',
  );

}